# Generated by Django 3.0.8 on 2020-07-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=500)),
                ('c_code', models.CharField(max_length=100)),
                ('c_address', models.CharField(max_length=1000)),
                ('c_description', models.CharField(max_length=1000)),
                ('c_logo', models.CharField(max_length=500)),
                ('i_main_branch', models.IntegerField(max_length=11)),
                ('i_parent_branch', models.IntegerField(max_length=11)),
                ('c_status', models.CharField(max_length=10)),
                ('d_created_at', models.DateTimeField(auto_now_add=True)),
                ('d_updated_at', models.DateTimeField(auto_now=True)),
                ('c_created_by', models.CharField(max_length=50)),
                ('c_updated_by', models.CharField(max_length=50)),
            ],
        ),
    ]
