# Generated by Django 3.0.8 on 2020-07-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_auto_20200729_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='I_class_id',
        ),
        migrations.RemoveField(
            model_name='class',
            name='id',
        ),
        migrations.RemoveField(
            model_name='section',
            name='I_section_id',
        ),
        migrations.RemoveField(
            model_name='section',
            name='id',
        ),
        migrations.AddField(
            model_name='class',
            name='i_class_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='section',
            name='i_section_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
