# Generated by Django 3.0.8 on 2020-07-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_auto_20200729_1545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
