# Generated by Django 3.0.8 on 2020-07-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_auto_20200729_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('i_class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_class_name', models.CharField(max_length=100)),
                ('c_description', models.CharField(max_length=1000)),
                ('i_branch_id', models.IntegerField()),
                ('c_status', models.CharField(max_length=10)),
                ('d_created_at', models.DateTimeField(auto_now_add=True)),
                ('d_updated_at', models.DateTimeField(auto_now=True)),
                ('c_created_by', models.CharField(max_length=50)),
                ('c_updated_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('i_section_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_section_name', models.CharField(max_length=100)),
                ('c_description', models.CharField(max_length=1000)),
                ('i_class_id', models.IntegerField()),
                ('c_status', models.CharField(max_length=10)),
                ('d_created_at', models.DateTimeField(auto_now_add=True)),
                ('d_updated_at', models.DateTimeField(auto_now=True)),
                ('c_created_by', models.CharField(max_length=50)),
                ('c_updated_by', models.CharField(max_length=50)),
            ],
        ),
    ]
