# Generated by Django 3.0.8 on 2020-07-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_class_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='i_class_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='i_section_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
